apiVersion: v1
kind: Service
metadata:
  name: prediction-microservice
spec:
  type: LoadBalancer
  selector:
    app: prediction-microservice
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-microservice
  template:
    metadata:
      labels:
        app: prediction-microservice
    spec:
      containers:
        - name: app
          image: dantesaggin/development
          ports:
            - name: web
              containerPort: 80
              protocol: TCP